import { UserModel } from '../modules/models';

export const ROUTES = {
  DASHBOARD: { path: '/', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  DASHBOARD_PROJECTS: { path: '/dashboard/projects', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  DASHBOARD_CLIENTS: { path: '/dashboard/clients', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  DASHBOARD_WORKERS: { path: '/dashboard/workers', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  CLIENT_WIZARD: { path: '/clients/wizard/:id/:step?', roleList: [] },
  CLIENT_INVITE: { path: '/clients/invite/:id', roleList: [] },
  CLIENT_DETAIL: { path: '/clients/detail/:id/:step?', roleList: [UserModel.Role.CLIENT_ADMIN] },
  CLIENT_LIST: { path: '/clients', roleList: [] },
  PROJECT_WIZARD: { path: '/projects/wizard/:id/:step?', roleList: [] },
  PROJECT_NEW_WIZARD: { path: '/projects/wizard-new/:id/:step?', roleList: [] },
  PROJECT_DETAIL: { path: '/projects/detail/:id/:step?', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  PROJECT_LIST: { path: '/projects', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  PROJECT_INVITATION: { path: '/projects/invitation/:id/:step?', roleList: [UserModel.Role.CLIENT_ADMIN] },
  PROCORE_MAPPING: { path: '/procore-clients/client-mapping/:id/:step?', roleList: [UserModel.Role.CLIENT_ADMIN] },
  WORKER_LIST: { path: '/workers', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  WORKER_WIZARD: { path: '/workers/wizard/:id', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  WORKER_DETAIL: { path: '/workers/detail/:id/:step?', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  INVENTORY_LIST: { path: '/inventory', roleList: [] },
  ACCESS_CONTROL_SYSTEM_WIZARD: { path: '/inventory/access-control-system/wizard/:id', roleList: [] },
  BADGE_PRINTER_SYSTEM_WIZARD: { path: '/inventory/badge-printing-system/wizard/:id', roleList: [] },
  ACCOUNT_SETTINGS: { path: '/account/settings', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  PAYMENT_SETTINGS: { path: '/payment/settings', roleList: [UserModel.Role.CLIENT_ADMIN] },
  INVOICE_LIST: { path: '/invoices', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  INVOICE_DETAIL: { path: '/invoices/:id', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
  REGISTER: { path: '/users/registration', roleList: [] },
  FORGOT_PASSWORD: { path: '/forgot-password', roleList: [] },
  RESET_PASSWORD: { path: '/users/reset-password', roleList: [] },
  ADMIN: { path: '/admin', roleList: [] },
  PROCORE_CLIENTS: { path: '/procore-clients', roleList: [] },
  CLIENT_ONBOARDING: { path: '/client-onboarding', roleList: [UserModel.Role.CLIENT_ADMIN] },
  SECURITY: { path: '/security', roleList: [] },
  REPORTS: { path: '/reports', roleList: [UserModel.Role.CLIENT_ADMIN, UserModel.Role.REGULAR_USER] },
};
